version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks: 
      - teste
  atividade03.api:
    image: fiap.atividade03.excluir:v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: 
      - ConnectionStrings:DefaultConnection=${CONNECTION_STRING}
      - RabbitLocal:Endereco=${ENDERECO}
      - RabbitLocal:Porta=${PORTA}
      - RabbitLocal:Usuario=${USUARIO}
      - RabbitLocal:Senha=${SENHA}

    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - teste
      
    depends_on:
      - rabbitmq

networks:
  teste:
    driver: bridge
    